---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: edc-demo-app
  namespace: flux-system
spec:
  image: ghcr.io/hkassaei/edc-demo-app
  secretRef:
    name: ghcr-creds
  interval: 1m0s

