---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workload-clusters
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./workload-clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

