apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra-blueprints/crossplane
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

