---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 1m0s
  path: ./infra-blueprints/deployment-artifacts/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system