apiVersion: apps/v1
kind: Deployment
metadata:
  name: edc-demo-app
  namespace: default
  labels:
    app.kubernetes.io/name: edc-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: edc-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edc-demo
    spec:
      serviceAccountName: edc-demo-app-sa
      containers:
      - name: edc-demo-app
        image: ghcr.io/hkassaei/edc-demo-app:v0.1.1 # {"$imagepolicy": "flux-system:edc-demo-app"}
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: ghcr-creds
---
apiVersion: v1
kind: Service
metadata:
  name: edc-demo-app-service
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: edc-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
