apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: edc-demo-app-gsa@gcprdpscdpochcppaasdev01-c304.iam.gserviceaccount.com
  namespace: default
  name: edc-demo-app-sa