apiVersion: platform.com/v1alpha1
kind: KubernetesClusterClaim
metadata:
  name: workload-cluster-1 #change this before applying the file
  namespace: default
  labels:
    provider: gcp-classic
    cluster: gke
spec:
  id: workload-cluster-1   #change this before applying the file
  compositionSelector:
    matchLabels:
      provider: gcp-classic
      cluster: gke
  parameters:
    version: "latest"
    nodeSize: medium
    nodeCount: 1
  writeConnectionSecretToRef:
    name: k8s-connection

# Guide to node sizes:
# small: e2-standard-2    # 2 vCPUs, 8 GiB memory
# medium: e2-standard-4   # 4 vCPUs, 16 GiB memory
# large: e2-standard-8    # 8 vCPUs, 32 GiB memory
# xlarge: e2-standard-16  # 16 vCPUs, 64 GiB memory
# 2xlarge: e2-standard-32  # 32 vCPUs, 128 GiB memory
