---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.database.platform.com
spec:
  group: database.platform.com
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
    - jdbc
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageSize:
                    type: integer
                  version:
                    type: string
                  flavor:
                    type: string
                  instanceName:
                    type: string
                  dbName:
                    type: string
                  autoMinorVersionUpgrade:
                    type: boolean
                  highAvailability:
                    type: boolean
                  registryDocker:
                    type: string
                  registryDockerRepo:
                    type: string
                  registryDockerSecret:
                    type: string
                  repoHelm:
                    type: string
                  repoHelmSecret:
                    type: string
                  namespace:
                    type: string
                  storageClassName:
                    type: string
                  dbSecret:
                    type: string
                  replicaCount:
                    type: integer
                  providerConfigName:
                    type: string
                required:
                  - flavor
            required:
              - parameters
